/**
 * @file
 * @brief		系统内核配置
 * @author		admin
 * @date		2023.07.27
 * @version	    v1.0
 * @par Copyright(c): All rights reserved.
*/

#ifndef __DRIVER_CONFIG_H_
#define __DRIVER_CONFIG_H_

#include <compiler_defs.h>

#define SYS_CLK			(16000000UL)					/*!< 系统时钟 */

/** GPIO电平 */
typedef enum {
    PLIB_LOW = 0, 					/*!< 低电平 */
    PLIB_HIGH = !PLIB_LOW			/*!< 高点平 */
} IO_LEVEL_E;

/** 使能标志 */
typedef enum {
    PLIB_DISABLE = 0, 				/*!< 不使能 */
    PLIB_ENABLE = !PLIB_DISABLE		/*!< 使能 */
} FUNC_EN_E;

/** 寄存器定义 */
SFR(PREG_P0, 0x80);
SFR(PREG_P1, 0x90);
SFR(PREG_P2, 0xA0);
SFR(PREG_AFIO_IE0, 0xC6);
SFR(PREG_AFIO_IE1, 0xC7);
SFR(PREG_GPIO_PINMUX0, 0xC9);
SFR(PREG_GPIO_PINMUX1, 0xCC);
SFR(PREG_GPIO_PINMUX2, 0xCD);
SFR(PREG_GPIO_PINMUX3, 0xCE);
SFR(PREG_GPIO_PINMUX4, 0xCF);
SFR(PREG_GPIO_CFG0, 0xD1);
SFR(PREG_GPIO_CFG1, 0xD2);
SFR(PREG_GPIO_CFG2, 0xD3);
SFR(PREG_GPIO_CFG3, 0xD4);
SFR(PREG_GPIO_CFG4, 0xD5);
SFR(PREG_GPIO_CFG5, 0xD6);
SFR(PREG_GPIO_CFG6, 0xD7);
SFR(PREG_GPIO_DRV1, 0xFA);
SFR(PREG_GPIO_DRV2, 0xFB);
SFR(PREG_GPIO_DRV3, 0xFC);
SFR(PREG_LED_CTRL, 0xE8);

SFR(PREG_ADC_CTRL2, 0x8F);
SFR(PREG_ADC_CTRL0, 0xAA);
SFR(PREG_ADC_CTRL1, 0xAB);
SFR(PREG_ADC_FLAG, 0xAC);
SFR(PREG_ADC0_L, 0xAD);
SFR(PREG_ADC0_H, 0xAE);
SFR(PREG_ADC1_L, 0xAF);
SFR(PREG_ADC1_H, 0xB1);
SFR(PREG_ADC2_L, 0xB2);
SFR(PREG_ADC2_H, 0xB3);
SFR(PREG_ADC3_L, 0xB4);
SFR(PREG_ADC3_H, 0xB5);
SFR(PREG_ADC4_L, 0xB6);
SFR(PREG_ADC4_H, 0xB7);
SFR(PREG_ADC5_L, 0xBA);
SFR(PREG_ADC5_H, 0xBC);
SFR(PREG_ADC_PWM_DLY, 0xC1);

SFR(PREG_CHG_CTRL 	, 0x94);
SFR(PREG_CHG_ISET, 0x95);
SFR(PREG_CHG_FLAG, 0x96);
SFR(PREG_CHG_STATUS, 0x97);

SFR(PREG_MIC_INI0 		, 0x9E);
SFR(PREG_MIC_INI1 		, 0x9F);
SFR(PREG_MIC_CTRL0  	, 0xA1);
SFR(PREG_MIC_CTRL1   	, 0xA2);
SFR(PREG_MIC_FLAG 		, 0xA3);
SFR(PREG_MIC_TRIG1  	, 0xA4);
SFR(PREG_MIC_TRIG2  	, 0xA5);
SFR(PREG_MIC_VAL0  	, 0xA6);
SFR(PREG_MIC_VAL1  	, 0xA7);

SFR(PREG_MOS_CFG  	 	, 0xD9);
SFR(PREG_MOS_CTRL  	, 0xDA);
SFR(PREG_MOS_PERIOD_L 	, 0xDB);
SFR(PREG_MOS_PERIOD_H 	, 0xDC);
SFR(PREG_MOS_DUTY_L  	, 0xDD);
SFR(PREG_MOS_DUTY_H  	, 0xDE);
SFR(PREG_MOS_IEN  	 	, 0xDF);
SFR(PREG_SENSOR_CTRL, 0xF6);

SFR(PREG_MOTOR_CTRL, 0xE7);

SFR(PREG_PWM0_CTRL, 0xE1);
SFR(PREG_PWM0_PERIOD, 0xE2);
SFR(PREG_PWM0_DUTY_CH0, 0xE3);
SFR(PREG_PWM0_DUTY_CH1, 0xE4);
SFR(PREG_PWM0_DUTY_CH2, 0xE5);
SFR(PREG_PWM_IEN 	, 0xE6);
SFR(PREG_PWM1_CTRL, 0xF1);
SFR(PREG_PWM1_PERIOD, 0xF2);
SFR(PREG_PWM1_DUTY_CH0, 0xF3);
SFR(PREG_PWM1_DUTY_CH1, 0xF4);
SFR(PREG_PWM1_DUTY_CH2, 0xF5);

SFR(PREG_DPL, 0x82);
SFR(PREG_DPH, 0x83);
SFR(PREG_PCON, 0x87);
SFR(PREG_CLK_SEL, 0xF9);
SFR(PREG_SYS_CTRL, 0x91);

SFR (PREG_ACC, 0xE0);

SFR(PREG_TMOD, 0x89);
SFR(PREG_TL0, 0x8A);
SFR(PREG_TL1, 0x8B);
SFR(PREG_TH0, 0x8C);
SFR(PREG_TH1, 0x8D);
SFR(PREG_CRCL1, 0xC2);
SFR(PREG_CRCH1, 0xC3);
SFR(PREG_CRCL0, 0xCA);
SFR(PREG_CRCH0, 0xCB);

SFR(PREG_UART_CTRL, 0x9B);
SFR(PREG_UART_S1BUF, 0x9C);
SFR(PREG_UART_BAUD_L, 0x9D);
SFR(PREG_UART_BAUD_H, 0xBB);

SFR(PREG_WK_CTRL   	, 0x98);
SFR(PREG_WK_TIMER_CFG, 0x99);

SFR(PREG_WDT_TIME, 0x86);

/** 位操作定义 */
SBIT(PBIT_GPIOA3, 0x80,  3);
SBIT(PBIT_GPIOA2, 0x80,  2);
SBIT(PBIT_GPIOA1, 0x80,  1);
SBIT(PBIT_GPIOA0, 0x80,  0);
SBIT(PBIT_GPIOB3, 0x90,  3);
SBIT(PBIT_GPIOB2, 0x90,  2);
SBIT(PBIT_GPIOB1, 0x90,  1);
SBIT(PBIT_GPIOB0, 0x90,  0);
SBIT(PBIT_GPIOC1, 0xA0,  1);
SBIT(PBIT_GPIOC0, 0xA0,  0);

SBIT(PBIT_TF1, 0x88,  7);
SBIT(PBIT_TR1, 0x88,  6);
SBIT(PBIT_TF0, 0x88,  5);
SBIT(PBIT_TR0, 0x88,  4);

SBIT(PBIT_EAL, 0xA8,  7);
SBIT(PBIT_ET1, 0xA8,  3);
SBIT(PBIT_ET0, 0xA8,  1);
SBIT(PBIT_EX0, 0xA8,  0);

SBIT(PBIT_WDTEN, 0xB8,  6);
SBIT(PBIT_EX6, 0xB8,  5);
SBIT(PBIT_EX5, 0xB8,  4);
SBIT(PBIT_EX3, 0xB8,  2);
SBIT(PBIT_EX2, 0xB8,  1);
SBIT(PBIT_EX7, 0xB8,  0);

SBIT(PBIT_ADC_TRIG, 0xC8,  6);

SFR(PREG_IEN2, 0x9A);

#endif /* end of __DRIVER_CONFIG_H_ */
